name: lodster

services:
  nginx:
    image: nginx:latest
    networks:
      - lodster-internal
      - rdt
    restart: unless-stopped
    volumes:
      - ./templates:/etc/nginx/templates:ro
      - ./dist:/usr/share/nginx/html:ro

  backend:
    image: gijsjan/lodster:1.0.0    
    networks:
      - lodster-internal

networks:
  lodster-internal:
  rdt:
    external: true
